name: CI/CD n8n

on:
  push:
    branches: ["main"]

env:
  REGION: us-central1
  PROJECT_ID: n8n-ads-spend
  REPO: n8n-repo
  SERVICE: metrics-api
  IMAGE_NAME: n8n

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-test@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev -q

      - name: Build and Push Docker image
        run: |
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}"
          TAG="${GITHUB_SHA::8}"
          docker build -t "$IMAGE:$TAG" .
          docker push "$IMAGE:$TAG"
          echo "IMAGE_URI=$IMAGE:$TAG" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image "$IMAGE_URI" \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --service-account cr-metrics@${{ env.PROJECT_ID }}.iam.gserviceaccount.com \
            --set-env-vars PROJECT_ID=${{ env.PROJECT_ID }},BQ_DATASET=ads_warehouse,BQ_TABLE=ads_spend_raw
